{% set name = "autouri" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44014c0adf28353d55660f259eb7e509a6fbe464e05873054ca73fa83d69ca30

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - pyopenssl
    - google-cloud-storage
    - boto3
    - awscli
    - dateparser
    - pytest
    - filelock

test:
  imports:
    - autouri

about:
  home: https://github.com/ENCODE-DCC/autouri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Recursive localization for various types of URIs
  description: |
    It is a Python API for recursively localizing file URIs
    (e.g. gs://. s3://, http:// and local path) on any target directory URI.
  dev_url: https://github.com/ENCODE-DCC/autouri

extra:
  recipe-maintainers:
    - leepc12
